(cl:defpackage robosapiens_tool-msg
  (:use )
  (:export
   "<ALL_CAMERA_DETECTION_INFO>"
   "ALL_CAMERA_DETECTION_INFO"
   "<BOX>"
   "BOX"
   "<CAMERA_BOX_DETECTION_CONFIDENCE>"
   "CAMERA_BOX_DETECTION_CONFIDENCE"
   "<CAMERAS_ID_CONFIDENCE>"
   "CAMERAS_ID_CONFIDENCE"
   "<POSE2DKEYPOINT>"
   "POSE2DKEYPOINT"
   "<POSECONFKPT2D>"
   "POSECONFKPT2D"
   "<POSE_DETECTION>"
   "POSE_DETECTION"
   "<BBOX>"
   "BBOX"
   "<ID_CONF>"
   "ID_CONF"
   "<IMG_BBOX_HEATMAP>"
   "IMG_BBOX_HEATMAP"
  ))

