// Generated by gencpp from file robosapiens_tool/bbox.msg
// DO NOT EDIT!


#ifndef ROBOSAPIENS_TOOL_MESSAGE_BBOX_H
#define ROBOSAPIENS_TOOL_MESSAGE_BBOX_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robosapiens_tool
{
template <class ContainerAllocator>
struct bbox_
{
  typedef bbox_<ContainerAllocator> Type;

  bbox_()
    : bbox()  {
    }
  bbox_(const ContainerAllocator& _alloc)
    : bbox(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<float, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<float>> _bbox_type;
  _bbox_type bbox;





  typedef boost::shared_ptr< ::robosapiens_tool::bbox_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robosapiens_tool::bbox_<ContainerAllocator> const> ConstPtr;

}; // struct bbox_

typedef ::robosapiens_tool::bbox_<std::allocator<void> > bbox;

typedef boost::shared_ptr< ::robosapiens_tool::bbox > bboxPtr;
typedef boost::shared_ptr< ::robosapiens_tool::bbox const> bboxConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robosapiens_tool::bbox_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robosapiens_tool::bbox_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robosapiens_tool::bbox_<ContainerAllocator1> & lhs, const ::robosapiens_tool::bbox_<ContainerAllocator2> & rhs)
{
  return lhs.bbox == rhs.bbox;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robosapiens_tool::bbox_<ContainerAllocator1> & lhs, const ::robosapiens_tool::bbox_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robosapiens_tool

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robosapiens_tool::bbox_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosapiens_tool::bbox_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosapiens_tool::bbox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosapiens_tool::bbox_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosapiens_tool::bbox_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosapiens_tool::bbox_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robosapiens_tool::bbox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74499d7e30e45661484dee816ec31e31";
  }

  static const char* value(const ::robosapiens_tool::bbox_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74499d7e30e45661ULL;
  static const uint64_t static_value2 = 0x484dee816ec31e31ULL;
};

template<class ContainerAllocator>
struct DataType< ::robosapiens_tool::bbox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robosapiens_tool/bbox";
  }

  static const char* value(const ::robosapiens_tool::bbox_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robosapiens_tool::bbox_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[] bbox # xmin, ymin, xmax, ymax\n"
;
  }

  static const char* value(const ::robosapiens_tool::bbox_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robosapiens_tool::bbox_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.bbox);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bbox_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robosapiens_tool::bbox_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robosapiens_tool::bbox_<ContainerAllocator>& v)
  {
    s << indent << "bbox[]" << std::endl;
    for (size_t i = 0; i < v.bbox.size(); ++i)
    {
      s << indent << "  bbox[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.bbox[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSAPIENS_TOOL_MESSAGE_BBOX_H
