// Generated by gencpp from file robosapiens_tool/Camera_Box_Detection_Confidence.msg
// DO NOT EDIT!


#ifndef ROBOSAPIENS_TOOL_MESSAGE_CAMERA_BOX_DETECTION_CONFIDENCE_H
#define ROBOSAPIENS_TOOL_MESSAGE_CAMERA_BOX_DETECTION_CONFIDENCE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robosapiens_tool
{
template <class ContainerAllocator>
struct Camera_Box_Detection_Confidence_
{
  typedef Camera_Box_Detection_Confidence_<ContainerAllocator> Type;

  Camera_Box_Detection_Confidence_()
    : camera_id()
    , detection(0)
    , confidence(0.0)  {
    }
  Camera_Box_Detection_Confidence_(const ContainerAllocator& _alloc)
    : camera_id(_alloc)
    , detection(0)
    , confidence(0.0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _camera_id_type;
  _camera_id_type camera_id;

   typedef int32_t _detection_type;
  _detection_type detection;

   typedef float _confidence_type;
  _confidence_type confidence;





  typedef boost::shared_ptr< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> const> ConstPtr;

}; // struct Camera_Box_Detection_Confidence_

typedef ::robosapiens_tool::Camera_Box_Detection_Confidence_<std::allocator<void> > Camera_Box_Detection_Confidence;

typedef boost::shared_ptr< ::robosapiens_tool::Camera_Box_Detection_Confidence > Camera_Box_Detection_ConfidencePtr;
typedef boost::shared_ptr< ::robosapiens_tool::Camera_Box_Detection_Confidence const> Camera_Box_Detection_ConfidenceConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator1> & lhs, const ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator2> & rhs)
{
  return lhs.camera_id == rhs.camera_id &&
    lhs.detection == rhs.detection &&
    lhs.confidence == rhs.confidence;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator1> & lhs, const ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robosapiens_tool

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c08e18ff46252dc459c88d05d53158ce";
  }

  static const char* value(const ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc08e18ff46252dc4ULL;
  static const uint64_t static_value2 = 0x59c88d05d53158ceULL;
};

template<class ContainerAllocator>
struct DataType< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robosapiens_tool/Camera_Box_Detection_Confidence";
  }

  static const char* value(const ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string camera_id\n"
"\n"
"int32 detection\n"
"\n"
"float32 confidence\n"
;
  }

  static const char* value(const ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.camera_id);
      stream.next(m.detection);
      stream.next(m.confidence);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Camera_Box_Detection_Confidence_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robosapiens_tool::Camera_Box_Detection_Confidence_<ContainerAllocator>& v)
  {
    s << indent << "camera_id: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.camera_id);
    s << indent << "detection: ";
    Printer<int32_t>::stream(s, indent + "  ", v.detection);
    s << indent << "confidence: ";
    Printer<float>::stream(s, indent + "  ", v.confidence);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSAPIENS_TOOL_MESSAGE_CAMERA_BOX_DETECTION_CONFIDENCE_H
