// Generated by gencpp from file robosapiens_tool/Pose2DKeypoint.msg
// DO NOT EDIT!


#ifndef ROBOSAPIENS_TOOL_MESSAGE_POSE2DKEYPOINT_H
#define ROBOSAPIENS_TOOL_MESSAGE_POSE2DKEYPOINT_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robosapiens_tool
{
template <class ContainerAllocator>
struct Pose2DKeypoint_
{
  typedef Pose2DKeypoint_<ContainerAllocator> Type;

  Pose2DKeypoint_()
    : kpt_name()
    , x(0)
    , y(0)  {
    }
  Pose2DKeypoint_(const ContainerAllocator& _alloc)
    : kpt_name(_alloc)
    , x(0)
    , y(0)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _kpt_name_type;
  _kpt_name_type kpt_name;

   typedef int32_t _x_type;
  _x_type x;

   typedef int32_t _y_type;
  _y_type y;





  typedef boost::shared_ptr< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> const> ConstPtr;

}; // struct Pose2DKeypoint_

typedef ::robosapiens_tool::Pose2DKeypoint_<std::allocator<void> > Pose2DKeypoint;

typedef boost::shared_ptr< ::robosapiens_tool::Pose2DKeypoint > Pose2DKeypointPtr;
typedef boost::shared_ptr< ::robosapiens_tool::Pose2DKeypoint const> Pose2DKeypointConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator1> & lhs, const ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator2> & rhs)
{
  return lhs.kpt_name == rhs.kpt_name &&
    lhs.x == rhs.x &&
    lhs.y == rhs.y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator1> & lhs, const ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robosapiens_tool

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6ce75e74f73663ed82a3235764bc7edf";
  }

  static const char* value(const ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6ce75e74f73663edULL;
  static const uint64_t static_value2 = 0x82a3235764bc7edfULL;
};

template<class ContainerAllocator>
struct DataType< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robosapiens_tool/Pose2DKeypoint";
  }

  static const char* value(const ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# This message contains all relevant information for a human pose 2D keypoint\n"
"\n"
"# The kpt_name according to https://github.com/Daniil-Osokin/lightweight-human-pose-estimation.pytorch\n"
"\n"
"string kpt_name\n"
"\n"
"# x and y pixel position on the input image, (0, 0) is top-left corner of image\n"
"int32 x\n"
"int32 y\n"
;
  }

  static const char* value(const ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.kpt_name);
      stream.next(m.x);
      stream.next(m.y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Pose2DKeypoint_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robosapiens_tool::Pose2DKeypoint_<ContainerAllocator>& v)
  {
    s << indent << "kpt_name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.kpt_name);
    s << indent << "x: ";
    Printer<int32_t>::stream(s, indent + "  ", v.x);
    s << indent << "y: ";
    Printer<int32_t>::stream(s, indent + "  ", v.y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOSAPIENS_TOOL_MESSAGE_POSE2DKEYPOINT_H
