# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from robosapiens_tool/Cameras_id_Confidence.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class Cameras_id_Confidence(genpy.Message):
  _md5sum = "c0d4772d7cc3a8c1b69088d5e653da29"
  _type = "robosapiens_tool/Cameras_id_Confidence"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """float32 camera1_conf

float32 camera2_conf

float32 camera3_conf

float32 camera4_conf
"""
  __slots__ = ['camera1_conf','camera2_conf','camera3_conf','camera4_conf']
  _slot_types = ['float32','float32','float32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       camera1_conf,camera2_conf,camera3_conf,camera4_conf

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Cameras_id_Confidence, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.camera1_conf is None:
        self.camera1_conf = 0.
      if self.camera2_conf is None:
        self.camera2_conf = 0.
      if self.camera3_conf is None:
        self.camera3_conf = 0.
      if self.camera4_conf is None:
        self.camera4_conf = 0.
    else:
      self.camera1_conf = 0.
      self.camera2_conf = 0.
      self.camera3_conf = 0.
      self.camera4_conf = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.camera1_conf, _x.camera2_conf, _x.camera3_conf, _x.camera4_conf))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.camera1_conf, _x.camera2_conf, _x.camera3_conf, _x.camera4_conf,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_4f().pack(_x.camera1_conf, _x.camera2_conf, _x.camera3_conf, _x.camera4_conf))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 16
      (_x.camera1_conf, _x.camera2_conf, _x.camera3_conf, _x.camera4_conf,) = _get_struct_4f().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_4f = None
def _get_struct_4f():
    global _struct_4f
    if _struct_4f is None:
        _struct_4f = struct.Struct("<4f")
    return _struct_4f
